### ISSUE TITLE
Bug in now_week calculation

### ISSUE THREAD

**Issue by mgedmin** [ProgrammersOfVilnius/gtimesheet#2]
Consider [this code  in tracker.py](https://github.com/ProgrammersOfVilnius/gtimesheet/blob/a351dc9a309219674f3a6026820243371df427ab/gtimesheet/tracker.py#L69):

``` python
    now = now or datetime.datetime.now()
    replog = replog or ReportsLog(now=now)
    now = arrow.get(now).floor('day').naive
    now_week = '%d/%02d' % (now.year, woty(now))
    now_month = now.strftime('%Y-%m')
```

Pass in a date like `datetime.date(2016, 1, 1)`.  The computed `now_week` will  be `'2016/53'`.  This is wrong: it should be `2015/53`.

The correct code would be to use `now.isocalendar()[0]` for the year, just like `now.isocalendar()[1]` is used for the week number.

**Comment by sirex** [comment]
@mgedmin thanks for the report, fixed.
